name: Node.js CI/CD

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.11.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/be-ai:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/be-ai:${IMAGE_TAG}
  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/be-ai:${{ github.sha }}
            docker stop be-ai || true
            docker rm be-ai || true
            docker run -d --name be-ai -p 8083:8083 -v /root/be-ai/.env:/home/node/app/.env ${{ secrets.DOCKER_USERNAME }}/be-ai:${{ github.sha }}
  
